CrowdStock/CrowdStock/Models/Stock.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Runtime.Serialization;

namespace CrowdStock.Models
{
	public class Stock
	{
		[Key]
		[Required]
		[StringLength(4)]
		[Display(Name = "Symbol")]
		[RegularExpression("^[A-Z]+$", ErrorMessage = "Symbol must be UPPERCASE")]
		public string Id { get; set; }

		[Required]
		[StringLength(50)]
		[Index]
		public string Name { get; set; }

		public string Description { get; set; }

		[JsonIgnore] // json
		[IgnoreDataMember] //xml
		public virtual ICollection<History> History { get; set; }

		[JsonIgnore] // json
		[IgnoreDataMember] //xml
		public virtual ICollection<Vote> Votes { get; set; }

		/// <summary>
		/// A decimal value between 0 and 1 which indicates how many users think that the stock price will be going up
		/// </summary>
		[Display(Name = "% Consensus")]
		[DisplayFormat(DataFormatString = "{0:P}", ApplyFormatInEditMode = false)]
		public double Consensus { get; set; }

		public void UpdateConsensus()
		{
			if(this.Votes == null)
			{
				this.Consensus = 0;
				return;
			}

			var futureVotes = from vote in this.Votes
							  where vote.EndDate > DateTime.Now
							  select vote.isPositive ? 1 : 0;

			if(!futureVotes.Any())
			{
				this.Consensus = 0;
				return;
			}

			this.Consensus = futureVotes.Average();
		}

		/// <summary>
		/// A decimal value between 0 and 100 which indicates how many users think that the stock price will be going up and
		/// based on the user's reputation
		/// </summary>
		[Display(Name = "% Optimism")]
		public double Optimism { get; set; }

		public void UpdateOptimism()
		{
			if(this.Votes == null)
			{
				this.Optimism = 0;
				return;
			}

			var futureVotes = from vote in this.Votes
							  where vote.EndDate > DateTime.Now
							  select vote;
			if(!futureVotes.Any())
			{
				this.Optimism = 0;
				return;
			}

			//This is the optimism to be returned
			double optimism = 0.0;
			//This is the total reputation of all the votes
			double totalRepuatation = 0.0;

			foreach(Vote v in futureVotes)
			{
				totalRepuatation += v.User.Reputation;
			}

			foreach(Vote v in futureVotes)
			{
				if(v.isPositive)
				{
					optimism += (v.User.Reputation / totalRepuatation);
				}
			}

			//This changes the value from a percentage to a decimal value from 0 to 100
			this.Optimism = (optimism * 100.00);
		}

		public byte[] Logo { get; set; }
	}
}

CrowdStock/CrowdStock/Models/VotePopupViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace CrowdStock.Models
{
	public enum VPType
	{
		CanVote,
		AlreadyVoted,
		VoteSubmitted,
		NotAuthorized
	}

	public class VotePopupViewModel
	{
		public VPType Type { get; set; }
		public string StockId { get; set; }

		[Display(Name="How many days?")]
		public int nDays { get; set; }

		[Display(Name="Up or Down?")]
		public bool isPositive { get; set; }
	}
}

CrowdStock/CrowdStock/Controllers/API/StocksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web.Http;
using System.Web.Http.Description;
using CrowdStock.Models;

namespace CrowdStock.Controllers.API
{
	public class StocksController : ApiController
	{
		private CrowdStockDBContext db = new CrowdStockDBContext();

		// GET: api/Stocks
		[Authorize(Roles="Administrator")]
		public IQueryable<StockApiViewModel> GetStocks()
		{
			var stocks = from stock in db.Stocks
						 orderby stock.Id
						 select new StockApiViewModel
						 {
							 Id = stock.Id,
							 Name = stock.Name,
							 Description = stock.Description,
							 LastHistory = stock.History.OrderByDescending(hist => hist.Date).FirstOrDefault()
						 };
			return stocks;
		}

		// GET: api/Stocks/5
		[ResponseType(typeof(Stock))]
		public async Task<IHttpActionResult> GetStock(string id)
		{
			Stock stock = await db.Stocks.FindAsync(id);
			if(stock == null)
			{
				return NotFound();
			}

			return Ok(new StockApiViewModel
			{
				Id = stock.Id,
				Name = stock.Name,
				Description = stock.Description,
				LastHistory = stock.History.OrderByDescending(hist => hist.Date).FirstOrDefault()
			});
		}
	}
}

CrowdStock/CrowdStock/Controllers/StocksController.cs
using CrowdStock.Models;
using Microsoft.AspNet.Identity;
using PagedList;
using System;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace CrowdStock.Controllers
{
	public class StocksController : Controller
	{
		private CrowdStockDBContext db = new CrowdStockDBContext();

		// GET: Stocks
		public ActionResult Index()
		{
			ViewBag.TopStocks = (from stock in db.Stocks.ToList()
								 orderby stock.Optimism descending
								 select stock).Take(25);

			ViewBag.TopUsers = (from user in db.Users.ToList()
								orderby user.Reputation descending
								select user).Take(25);

			return View();
		}

		public ActionResult List(int? page)
		{
			var stocks = db.Stocks.OrderBy(s => s.Id);
			return View(stocks.ToPagedList(page ?? 1, 25));
		}
		public ActionResult ListUsers(int? page)
		{
			var users = db.Users.OrderBy(user => user.Reputation);
			return View(users.ToPagedList(page ?? 1, 25));
		}

        [AllowAnonymous]
        public ActionResult Logo(string id)
        {
            if (string.IsNullOrWhiteSpace(id))
                return HttpNotFound();

            using (var db = new CrowdStockDBContext())
            {
                var stock = db.Stocks.Find(id);
                if (stock == null)
                    return HttpNotFound();
                if (stock.Logo != null)
                    return File(stock.Logo, "image/gif");
                else
                    return File(Server.MapPath("~/Content/img/whiteImage.gif"), "image/gif");
            }
        }

		// GET: Stocks/Details/5
		public async Task<ActionResult> Details(string id)
		{
			if(id == null)
			{
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
			}
			Stock stock = await db.Stocks.FindAsync(id);
			if(stock == null)
			{
				return HttpNotFound();
			}

			var user = db.Users.Find(User.Identity.GetUserId());
			if(user == null)
			{
				ViewBag.CurrentVote = new VoteViewModel();
			}
			else
			{
				var currentVote = (from vote in user.Votes
								   where vote.StockId.ToUpper() == id.ToUpper()
								   && vote.EndDate > DateTime.Now
								   select vote).SingleOrDefault();

				if(currentVote == null)
				{
					ViewBag.CurrentVote = new VoteViewModel { VoteActive = false, StockId = id.ToUpper() };
				}
				else
				{
					ViewBag.CurrentVote = new VoteViewModel
					{
						VoteActive = true,
						Id = currentVote.Id,
						UserId = currentVote.UserId,
						StockId = currentVote.StockId,
						isPositive = currentVote.isPositive,
						Date = currentVote.Date,
						EndDate = currentVote.EndDate,
						User = currentVote.User,
						Stock = currentVote.Stock,
						IsCorrect = currentVote.IsCorrect
					};
				}
			}

			return View(stock);
		}

		// GET: Stocks/Create
		[Authorize(Roles = "Administrator")]
		public ActionResult Create()
		{
			return View();
		}

		// POST: Stocks/Create
		// To protect from overposting attacks, please enable the specific properties you want to bind to, for
		// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateAntiForgeryToken]
		[Authorize(Roles = "Administrator")]
		public async Task<ActionResult> Create([Bind(Include = "Id,Name,Description")] Stock stock)
		{
			if(ModelState.IsValid)
			{
				db.Stocks.Add(stock);
				await db.SaveChangesAsync();
				return RedirectToAction("List");
			}

			return View(stock);
		}

		// GET: Stocks/Edit/5
		[Authorize(Roles = "Administrator")]
		public async Task<ActionResult> Edit(string id)
		{
			if(id == null)
			{
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
			}
			Stock stock = await db.Stocks.FindAsync(id);
			if(stock == null)
			{
				return HttpNotFound();
			}
			return View(stock);
		}

		// POST: Stocks/Edit/5
		// To protect from overposting attacks, please enable the specific properties you want to bind to, for
		// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateAntiForgeryToken]
		[Authorize(Roles = "Administrator")]
		public async Task<ActionResult> Edit([Bind(Include = "Id,Name,Description")] Stock stock)
		{
			if(ModelState.IsValid)
			{
				db.Entry(stock).State = EntityState.Modified;
				await db.SaveChangesAsync();
				return RedirectToAction("List");
			}
			return View(stock);
		}

		// GET: Stocks/Delete/5
		[Authorize(Roles = "Administrator")]
		public async Task<ActionResult> Delete(string id)
		{
			if(id == null)
			{
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
			}
			Stock stock = await db.Stocks.FindAsync(id);
			if(stock == null)
			{
				return HttpNotFound();
			}
			return View(stock);
		}

		// POST: Stocks/Delete/5
		[HttpPost, ActionName("Delete")]
		[ValidateAntiForgeryToken]
		[Authorize(Roles = "Administrator")]
		public async Task<ActionResult> DeleteConfirmed(string id)
		{
			Stock stock = await db.Stocks.FindAsync(id);
			db.Stocks.Remove(stock);
			await db.SaveChangesAsync();
			return RedirectToAction("List");
		}

		public async Task<ActionResult> VotePopup(string id)
		{
			if(!User.Identity.IsAuthenticated)
				return View(new VotePopupViewModel { Type = VPType.NotAuthorized });

			var stock = await db.Stocks.FindAsync(id.ToUpper());
			if(stock == null)
				return HttpNotFound();

			var currentVotes = from vote in stock.Votes
							   where vote.UserId == User.Identity.GetUserId()
							   && vote.EndDate > DateTime.Now
							   select vote;

			if(currentVotes.Any())
				return View(new VotePopupViewModel { Type = VPType.AlreadyVoted });

			return View(new VotePopupViewModel
			{
				Type = VPType.CanVote,
				StockId = stock.Id.ToUpper()
			});
		}

		[HttpPost]
		public async Task<ActionResult> VotePopup(VotePopupViewModel model)
		{
			if(!User.Identity.IsAuthenticated)
				return View(new VotePopupViewModel { Type = VPType.NotAuthorized });

			var stock = await db.Stocks.FindAsync(model.StockId.ToUpper());
			if(stock == null)
				return HttpNotFound();

			var currentVotes = from vote in stock.Votes
							   where vote.UserId == User.Identity.GetUserId()
							   && vote.EndDate > DateTime.Now
							   select vote;

			if(currentVotes.Any())
				return View(new VotePopupViewModel { Type = VPType.AlreadyVoted });

			if(model.nDays <= 0)
			{
				ModelState.AddModelError("", "Days must be > 0");
				return View(model);
			}

			Vote newVote = new Vote
			{
				Date = DateTime.Now,
				EndDate = DateTime.Now.AddDays(model.nDays),
				StockId = stock.Id,
				UserId = User.Identity.GetUserId(),
				isPositive = model.isPositive
			};
			db.Votes.Add(newVote);
			db.SaveChanges();

			model.Type = VPType.VoteSubmitted;
			return View(model);
		}

		protected override void Dispose(bool disposing)
		{
			if(disposing)
			{
				db.Dispose();
			}
			base.Dispose(disposing);
		}
	}
}

CrowdStock/CrowdStock/Controllers/UsersController.cs
using CrowdStock.Models;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace CrowdStock.Controllers
{
	public class UsersController : Controller
	{
		private CrowdStockDBContext db = new CrowdStockDBContext();

		// GET: Users
		public ActionResult Index()
		{
			ViewBag.TopUsers = db.Users.OrderByDescending(u => u.Reputation).Take(100);
			return View();
		}

		// GET: Users/Details/5
		public ActionResult Details(string id)
		{
			if(id == null)
			{
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
			}
			ApplicationUser applicationUser = db.Users.Find(id);
			if(applicationUser == null)
			{
				return HttpNotFound();
			}
			return View(applicationUser);
		}

		protected override void Dispose(bool disposing)
		{
			if(disposing)
			{
				db.Dispose();
			}
			base.Dispose(disposing);
		}
	}
}

CrowdStock/CrowdStock/Views/Stocks/Create.cshtml
@model CrowdStock.Models.Stock

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Stock</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Id, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CrowdStock/CrowdStock/Views/Stocks/Delete.cshtml
@model CrowdStock.Models.Stock

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Stock</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

CrowdStock/CrowdStock/Views/Stocks/Details.cshtml
@model CrowdStock.Models.Stock

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <div class="row">
        <div class="col-md-4">
            <h4>
                @Model.Id
            </h4>
        </div>
        <div class="col-md-4 col-md-offset-4 text-right">
            <img src="@Url.Action("Logo", "Stocks", new { id = Model.Id })" alt="@Model.Id logo" />
        </div>
    </div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>

    <div id="container" style="height: 400px; min-width: 310px"></div>

    <div class="VotePartial">
        @{Html.RenderPartial("VotePartial", ViewBag.CurrentVote as CrowdStock.Models.VoteViewModel);}
    </div>

    <h4>History</h4>
    <hr />
    <table class="table table-striped table-condensed">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.History.FirstOrDefault().Date)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.History.FirstOrDefault().Value)
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach(var hist in Model.History.OrderByDescending(h => h.Date).Take(10))
            {
                <tr>
                    <td>
                        @Html.DisplayFor(x => hist.Date)
                    </td>
                    <td>
                        @Html.DisplayFor(x => hist.Value)
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>
<br />
<br />
<p>
    @if(User.IsInRole("Administrator"))
    {
        <text>@Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |</text>
    }
    @Html.ActionLink("Back to List", "Index")
</p>

@section Scripts {
    @Scripts.Render("~/bundles/highcharts")
    <script type="text/javascript">
        $(function () {

            $.getJSON('@Url.RouteUrl("DefaultApi", new { httproute = "", controller = "History", stock = @Model.Id })', function (data) {
                // Create the chart
                $('#container').highcharts('StockChart', {

                    rangeSelector: {
                        selected: 1,
                        inputEnabled: $('#container').width() > 480
                    },

                    title: {
                        text: '@Model.Id Stock Price'
                    },

                    series: [{
                        name: '@Model.Id',
                        data: formatData(data),
                        tooltip: {
                            valueDecimals: 2
                        }
                    }]
                });
            });

        });

        function formatData(data) {
            var newData = [];
            for (var i = 0; i < data[0].length; i++) {
                newData.push([Date.parse(data[0][i].Date).valueOf(), data[0][i].Value]);
            }
            newData.reverse();
            return newData;
        }
    </script>
}

CrowdStock/CrowdStock/Views/Stocks/Edit.cshtml
@model CrowdStock.Models.Stock

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Stock</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CrowdStock/CrowdStock/Views/Stocks/Index.cshtml
@using Microsoft.AspNet.Identity
@{
    ViewBag.Title = "Index";
}

<div class="container">
    <br />
    <div class="form-group">
        <div id="searchTextField">
            <input class="form-control typeahead" type="text" placeholder="Search">
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-6">
        <h3>Top Stocks</h3>
        @{Html.RenderPartial("StocksPartial", ViewBag.TopStocks as IEnumerable<CrowdStock.Models.Stock>);}
    </div>
    <div class="col-md-6">
        <h3>Top Users</h3>
        @{Html.RenderPartial("UsersPartial", ViewBag.TopUsers as IEnumerable<CrowdStock.Models.ApplicationUser>);}
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/typeaheadbundle")
    <script type="text/javascript">

    var baseUrl = "@Url.Content("~/")";
    var apiUrl = "api/Search/%QUERY";
    var stockOn = false;
    var userOn = false;

    $(document).ready(function () {
        var stockAndusers = new Bloodhound({
            datumTokenizer: Bloodhound.tokenizers.obj.whitespace('Name'),
            queryTokenizer: Bloodhound.tokenizers.whitespace,
            remote: baseUrl + apiUrl
        });

        stockAndusers.initialize();

        $('#searchTextField .typeahead').typeahead(null, {
            name: 'stockAndusers',
            displayKey: 'Name',
            source: stockAndusers.ttAdapter(),
            templates: {
                empty: [
                    '<div class="empty-message">',
                    'No Matches',
                    '</div>'
                ].join('\n'),
                suggestion: Handlebars.compile([
                    '<p>',
                    '{{#compare Type "stock"}}',
                    '{{Name}} <em>({{Id}})</em>',
                    '{{/compare}}',
                    '{{#compare Type "user"}}',
                    '{{Name}}',
                    '{{/compare}}'
                ].join('\n'))
            }
        });

        $(document).on('typeahead:selected', '#searchTextField .typeahead', function (event, item, dataset) {
            if (item.Type == "user") {
                window.location.href = "@Url.Action("Details", "Users", new { id = "ID" })".replace("ID", item.Id);
            }
            else if (item.Type == "stock") {
                window.location.href = "@Url.Action("Details", "Stocks", new { id = "ID" })".replace("ID", item.Id);
                }
            });

        });


        $(".btn-vote").click(function() {
            console.log($(this));
        });
        
        $(".btn-vote").popover({
            html: true,
            content: function () {
                return '<iframe width="300" height="90" src="@Url.Action("VotePopup","Stocks")/'+$(this).attr('data-stock')+'" seamless frameborder="0" sandbox="allow-forms allow-same-origin allow-scripts">Loading...</iframe>';
            },
            title: function () {
                return "Vote on <em>" + $(this).attr('data-stock') + "</em>"
                /*
                + "<button type =\"button\" id = \"btn-close\" class = \"btn btn-primary pull-right btn-xs\">"+
                "<span class=\"glyphicon glyphicon-remove\"></span></button>"
                +"<br><br>"
                */;
            }
        });
    </script>
}

CrowdStock/CrowdStock/Views/Stocks/ListUsers.cshtml
@model PagedList.IPagedList<CrowdStock.Models.ApplicationUser>
@using PagedList.Mvc
@{
    ViewBag.Title = "ListUsers";
}

<h2>Users</h2>

<table class="table table-condensed table-striped">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FirstOrDefault().Reputation)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstOrDefault().AverageScore)
            </th>
            <th>@*Avatar goes here*@</th>
            <th>
                @Html.DisplayNameFor(model => model.FirstOrDefault().UserName)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <strong>@Html.DisplayFor(modelItem => item.Reputation)</strong>
                </td>
                <td>
                    <em>@Html.DisplayFor(modelItem => item.AverageScore)</em>
                </td>
                <td class="td-avatar" style="padding-top:0;padding-bottom:0;">
                    <img src="@Url.Action("Image","Account",new {id=item.Id})" alt="@item.UserName" class="avatar-table" />
                </td>
                <td>
                    <a href="@Url.Action("Details","Users",new {id=item.Id})">
                        @Html.DisplayFor(modelItem => item.UserName)
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>

@Html.PagedListPager(Model, page => Url.Action("ListUsers", new { page }))

CrowdStock/CrowdStock/Views/Stocks/VotePopup.cshtml
@model CrowdStock.Models.VotePopupViewModel
@using CrowdStock.Models;

@{Layout = null;}


<!doctype html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Vote</title>
    @Styles.Render("~/Content/css")
    <style type="text/css">
        body {
            background-color: #333333;
        }

        .voting-arrow, .voting-arrow:hover, .voting-arrow:focus {
            color: lightgrey;
            cursor: pointer;
        }

            .voting-arrow[data-selected] {
                color: orange;
            }
    </style>
</head>
<body style="padding: 10px;">
    @switch(Model.Type)
    {
        case VPType.NotAuthorized:
            <div class="alert alert-info">Please login</div>
            /*
            <a class="btn btn-primary" href="@Url.Action("Login","Account")">Login</a>
            
             <button type ="button" id = "btnclose" class = "btn btn-primary pull-right btn-xs">
                <span class="glyphicon glyphicon-remove"></span>
            </button>
            */
            break;
        case VPType.VoteSubmitted:
            <div class="alert alert-success">Vote Submitted</div>
            break;
        case VPType.AlreadyVoted:
            <div class="alert alert-info">You have already voted</div>
            break;
        case VPType.CanVote:
            using(Html.BeginForm("VotePopup", "Stocks", FormMethod.Post, new { @class = "form-inline" }))
            {
                <span class="voting-arrow" data-value="true"><span class="glyphicon glyphicon-arrow-up"></span></span>
                <span class="voting-arrow" data-value="false"><span class=" glyphicon glyphicon-arrow-down"></span></span>
                <input type="text" id="nDays" name="nDays" class="form-control" min="1" placeholder="# of Days" max="14" style="width:100px; display:inline-block;" />

                <input type="hidden" id="isPositive" name="isPositive" />

                @Html.HiddenFor(model => model.StockId)

                <input type="submit" id="submit" class="btn btn-primary" disabled />
            }
            break;
    }
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script type="text/javascript">
        $(".voting-arrow").click(function () {
            $('#isPositive').val($(this).attr("data-value"));
            $('.voting-arrow').removeAttr("data-selected");
            $(this).attr("data-selected", "");
            checkInput();
        });

        $('#nDays').change(checkInput);

        function checkInput() {
            if ($("#isPositive").val().length > 0 && !isNaN($('#nDays').val()) && $('#nDays').val() > 0)
                $('#submit').removeAttr("disabled");
            else
                $('#submit').attr("disabled", "");
        }
        /*
        $("#btnclose").click(function () {
            console.log("Yo, here2.");
            $(".btn-vote").popover('hide');
        });
        */
    </script>
</body>
</html>